# Generated by Django 5.2.14 on 2026-05-26 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sport", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("location_url", models.URLField(blank=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("max_players", models.IntegerField(blank=True, null=True)),
                ("cost_per_player", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("rsvp_token", models.CharField(blank=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "games",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="GameParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rsvp_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("maybe", "Maybe"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game_participants",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.IntegerField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "game_waitlist",
                "ordering": ["position"],
            },
        ),
    ]
