# Generated by Django 5.2.14 on 2026-05-26 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="games", to="groups.group"
            ),
        ),
        migrations.AddField(
            model_name="gameparticipant",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gameparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["group", "date"], name="games_group_i_7c7d31_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["date", "status"], name="games_date_cffa07_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gameparticipant",
            unique_together={("game", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="waitlist",
            unique_together={("game", "user")},
        ),
    ]
