# Generated by Django 5.2.14 on 2026-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
